/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PrimaryCta = {
  label?: string;
  href?: string;
};

export type SecondaryCta = {
  label?: string;
  href?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LogoImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "logo.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type CaseStudyBlocks = Array<
  | ({
      _key: string;
    } & TextSection)
  | ({
      _key: string;
    } & Pullquote)
  | ({
      _key: string;
    } & Cards)
  | ({
      _key: string;
    } & ImageGroup)
  | ({
      _key: string;
    } & LogoStrip)
>;

export type PageBlocks = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & TextSection)
  | ({
      _key: string;
    } & Pullquote)
  | ({
      _key: string;
    } & Cards)
  | ({
      _key: string;
    } & ImageGroup)
  | ({
      _key: string;
    } & LogoStrip)
  | ({
      _key: string;
    } & CaseStudyGrid)
  | ({
      _key: string;
    } & ContactBlock)
>;

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ContactBlock = {
  _type: "contactBlock";
  headline?: string;
  body?: RichText;
  email?: string;
  linkedin?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  anchor?: string;
};

export type LogoStrip = {
  _type: "logoStrip";
  heading?: string;
  logos?: Array<{
    image?: LogoImage;
    name?: string;
    url?: string;
    _type: "logo";
    _key: string;
  }>;
  anchor?: string;
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type CaseStudyGrid = {
  _type: "caseStudyGrid";
  heading?: string;
  source?: "all" | "picked";
  items?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  anchor?: string;
};

export type Cards = {
  _type: "cards";
  heading?: string;
  intro?: RichText;
  items?: Array<{
    title?: string;
    body?: string;
    _type: "card";
    _key: string;
  }>;
  anchor?: string;
};

export type ImageGroup = {
  _type: "imageGroup";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  caption?: string;
  anchor?: string;
};

export type Pullquote = {
  _type: "pullquote";
  text?: string;
  attribution?: string;
  anchor?: string;
};

export type TextSection = {
  _type: "textSection";
  tag?: string;
  heading?: string;
  body?: RichText;
  pullquote?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  anchor?: string;
};

export type Hero = {
  _type: "hero";
  headline?: string;
  subline?: string;
  primaryCta?: PrimaryCta;
  secondaryCta?: SecondaryCta;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  nav?: Array<{
    label?: string;
    href?: string;
    _type: "navItem";
    _key: string;
  }>;
  cta?: {
    label?: string;
    href?: string;
  };
  seoDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  context?: {
    client?: string;
    clientFull?: string;
    year?: string;
    role?: string;
    industry?: string;
  };
  blocks?: CaseStudyBlocks;
  preview?: {
    title?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  blocks?: PageBlocks;
  seoTitle?: string;
  seoDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PrimaryCta
  | SecondaryCta
  | SanityImageAssetReference
  | LogoImage
  | CaseStudyBlocks
  | PageBlocks
  | RichText
  | ContactBlock
  | LogoStrip
  | CaseStudyReference
  | CaseStudyGrid
  | Cards
  | ImageGroup
  | Pullquote
  | TextSection
  | Hero
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | CaseStudy
  | Slug
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    seoTitle,    seoDescription,    shareImage {  ...,  asset->{ _id, metadata { lqip, dimensions } }},    blocks[]{  ...,  _type == "hero" => { image {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "textSection" => { images[] {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "contactBlock" => { image {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "imageGroup" => { images[] {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "logoStrip" => { logos[]{ ..., image {  ...,  asset->{ _id, metadata { lqip, dimensions } }} } },  _type == "caseStudyGrid" => {    "cards": select(      source == "picked" => items[]-> {  _id,  title,  "slug": slug.current,  "client": context.client,  "cardTitle": coalesce(preview.title, title),  "image": coalesce(preview.image, heroImage) {  ...,  asset->{ _id, metadata { lqip, dimensions } }}},      *[_type == "caseStudy" && defined(slug.current)] | order(orderRank asc) {  _id,  title,  "slug": slug.current,  "client": context.client,  "cardTitle": coalesce(preview.title, title),  "image": coalesce(preview.image, heroImage) {  ...,  asset->{ _id, metadata { lqip, dimensions } }}}    )  }}  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  shareImage: {
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  blocks: Array<
    | {
        _key: string;
        _type: "cards";
        heading?: string;
        intro?: RichText;
        items?: Array<{
          title?: string;
          body?: string;
          _type: "card";
          _key: string;
        }>;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "caseStudyGrid";
        heading?: string;
        source?: "all" | "picked";
        items?: Array<
          {
            _key: string;
          } & CaseStudyReference
        >;
        anchor?: string;
        cards: Array<{
          _id: string;
          title: string | null;
          slug: string | null;
          client: string | null;
          cardTitle: string | null;
          image:
            | {
                asset: {
                  _id: string;
                  metadata: {
                    lqip: string | null;
                    dimensions: SanityImageDimensions | null;
                  } | null;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                _type: "image";
              }
            | {
                asset: {
                  _id: string;
                  metadata: {
                    lqip: string | null;
                    dimensions: SanityImageDimensions | null;
                  } | null;
                } | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              }
            | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "contactBlock";
        headline?: string;
        body?: RichText;
        email?: string;
        linkedin?: string;
        image: {
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        } | null;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "hero";
        headline?: string;
        subline?: string;
        primaryCta?: PrimaryCta;
        secondaryCta?: SecondaryCta;
        image: {
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        } | null;
      }
    | {
        _key: string;
        _type: "imageGroup";
        images: Array<{
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }> | null;
        caption?: string;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "logoStrip";
        heading?: string;
        logos: Array<{
          image: {
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
            media?: unknown; // Unable to locate the referenced type "logo.image.media" in schema
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          name?: string;
          url?: string;
          _type: "logo";
          _key: string;
        }> | null;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "pullquote";
        text?: string;
        attribution?: string;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "textSection";
        tag?: string;
        heading?: string;
        body?: RichText;
        pullquote?: string;
        images: Array<{
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }> | null;
        anchor?: string;
      }
  > | null;
} | null;

// Source: sanity/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    subtitle,    heroImage {  ...,  asset->{ _id, metadata { lqip, dimensions } }},    heroLogo {  ...,  asset->{ _id, metadata { lqip, dimensions } }},    context,    blocks[]{  ...,  _type == "hero" => { image {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "textSection" => { images[] {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "contactBlock" => { image {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "imageGroup" => { images[] {  ...,  asset->{ _id, metadata { lqip, dimensions } }} },  _type == "logoStrip" => { logos[]{ ..., image {  ...,  asset->{ _id, metadata { lqip, dimensions } }} } },  _type == "caseStudyGrid" => {    "cards": select(      source == "picked" => items[]-> {  _id,  title,  "slug": slug.current,  "client": context.client,  "cardTitle": coalesce(preview.title, title),  "image": coalesce(preview.image, heroImage) {  ...,  asset->{ _id, metadata { lqip, dimensions } }}},      *[_type == "caseStudy" && defined(slug.current)] | order(orderRank asc) {  _id,  title,  "slug": slug.current,  "client": context.client,  "cardTitle": coalesce(preview.title, title),  "image": coalesce(preview.image, heroImage) {  ...,  asset->{ _id, metadata { lqip, dimensions } }}}    )  }}  }
export type CASE_STUDY_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  heroImage: {
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroLogo: {
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  context: {
    client?: string;
    clientFull?: string;
    year?: string;
    role?: string;
    industry?: string;
  } | null;
  blocks: Array<
    | {
        _key: string;
        _type: "cards";
        heading?: string;
        intro?: RichText;
        items?: Array<{
          title?: string;
          body?: string;
          _type: "card";
          _key: string;
        }>;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "imageGroup";
        images: Array<{
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }> | null;
        caption?: string;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "logoStrip";
        heading?: string;
        logos: Array<{
          image: {
            asset: {
              _id: string;
              metadata: {
                lqip: string | null;
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
            media?: unknown; // Unable to locate the referenced type "logo.image.media" in schema
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          name?: string;
          url?: string;
          _type: "logo";
          _key: string;
        }> | null;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "pullquote";
        text?: string;
        attribution?: string;
        anchor?: string;
      }
    | {
        _key: string;
        _type: "textSection";
        tag?: string;
        heading?: string;
        body?: RichText;
        pullquote?: string;
        images: Array<{
          asset: {
            _id: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }> | null;
        anchor?: string;
      }
  > | null;
} | null;

// Source: sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    name,    nav[]{ label, href },    cta { label, href },    seoDescription,    shareImage {  ...,  asset->{ _id, metadata { lqip, dimensions } }}  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string | null;
  nav: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  cta: {
    label: string | null;
    href: string | null;
  } | null;
  seoDescription: string | null;
  shareImage: {
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)].slug.current
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current) && slug.current != "home"].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    seoTitle,\n    seoDescription,\n    shareImage {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n},\n    blocks[]{\n  ...,\n  _type == "hero" => { image {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "textSection" => { images[] {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "contactBlock" => { image {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "imageGroup" => { images[] {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "logoStrip" => { logos[]{ ..., image {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} } },\n  _type == "caseStudyGrid" => {\n    "cards": select(\n      source == "picked" => items[]-> {\n  _id,\n  title,\n  "slug": slug.current,\n  "client": context.client,\n  "cardTitle": coalesce(preview.title, title),\n  "image": coalesce(preview.image, heroImage) {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n}\n},\n      *[_type == "caseStudy" && defined(slug.current)] | order(orderRank asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  "client": context.client,\n  "cardTitle": coalesce(preview.title, title),\n  "image": coalesce(preview.image, heroImage) {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n}\n}\n    )\n  }\n}\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    subtitle,\n    heroImage {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n},\n    heroLogo {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n},\n    context,\n    blocks[]{\n  ...,\n  _type == "hero" => { image {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "textSection" => { images[] {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "contactBlock" => { image {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "imageGroup" => { images[] {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} },\n  _type == "logoStrip" => { logos[]{ ..., image {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n} } },\n  _type == "caseStudyGrid" => {\n    "cards": select(\n      source == "picked" => items[]-> {\n  _id,\n  title,\n  "slug": slug.current,\n  "client": context.client,\n  "cardTitle": coalesce(preview.title, title),\n  "image": coalesce(preview.image, heroImage) {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n}\n},\n      *[_type == "caseStudy" && defined(slug.current)] | order(orderRank asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  "client": context.client,\n  "cardTitle": coalesce(preview.title, title),\n  "image": coalesce(preview.image, heroImage) {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n}\n}\n    )\n  }\n}\n  }\n': CASE_STUDY_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0]{\n    name,\n    nav[]{ label, href },\n    cta { label, href },\n    seoDescription,\n    shareImage {\n  ...,\n  asset->{ _id, metadata { lqip, dimensions } }\n}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && defined(slug.current)].slug.current\n': CASE_STUDY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current) && slug.current != "home"].slug.current\n': PAGE_SLUGS_QUERY_RESULT;
  }
}
